openapi: 3.0.0
info:
  title: API Operaciones
  description: "# Introduccion\nAPI HTTP que sirve para la creación y calculo de operaciones suma. 
    Al ser una aplicacion construida sobre el chasis Platform la misma hereda el modulo de HealthCheck. A continuacion se detallan las operaciones de la misma."
  version: v1.0.0
  contact:
    name: Cristian Torres
    email: ctorres@andreani.com
paths:
  /info:
    get:
        tags:
          - Info
        summary: Obtiene informacion de la aplicacion.
        description: Permite obtener informacion de la aplicacion.
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                 $ref: '#/components/schemas/Info'
  /health:
    get:
        tags:
          - Health
        summary: Obtiene informacion de la salud. 
        description: Permiter obtener informacion sobre la salud de la aplicacion y sus componentes internos.
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                 $ref: '#/components/schemas/HealthCheck'  
  /resultados/{id}:
    get:
      tags:
        - resultados
      summary: obtiene un resultado
      description: Permite obtener el resultado de una operacion.
      parameters:
          - in: path
            name: id   
            required: true
            schema:
              type: string
              minimum: 1
            description: id de la operacion
      responses:
        200:
          description: retorna el resultado de la operacion
          content:
           application/json:
            schema:
             $ref: '#/components/schemas/Resultado'
        404:
           description: El resultado con el idOperacion no fue encontrado
  /operaciones:
    post:
      tags:
        - operaciones
      summary: crea una operacion
      description: Permite crear una operacion.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operacion'
      responses:
        202:
          description: Accepted
          headers:
            Location:
              schema:  
                type: string
                format: url
              description: link que obtiene el resultado de la operacion
        422:
          description: UnprocessableEntity
components:
  schemas:
    Info:
      type: object
      properties:
        details:
          type: object
          properties:
            applicationName:
              type: string
            version:
              type: string
            location:
              type: string
            runtimeVersion:
              type: string
            frameworkDescription:
                type: string
            oSDescription:
                type: string    
    HealthCheck:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: string
              enum:
                - DOWN
                - UP
                - UNKNOWN
                - OUT_OF_SERVICE
            description:
              type: string
        details:
          type: object
          additionalProperties: true  
    Resultado:
      type: object
      properties:
        id:
          type: string
        resultado:
          type: number
    Operacion:  
      type: object
      properties:
        firstValue:
          type: number
        secondValue:
          type: number
        type:
          type: string
          
    Location:
      type: object
      description: The number of requests left for the time window.
      properties:
        descripcion:
          type: string
        link:
          type: string

   

